### ISSUE TITLE
UI Performance

### ISSUE THREAD

**Issue by dalgleish** [imdone/imdone-atom#183]
I really like this package. But I've had to disable it because the performance loading the Tasks is terrible.

It seems related to number of tasks, because when I open a new window and load a simple project, although ⌥T is still slow, after loading it seems ok.

I realize it has to parse all the files to find `TODO` and such, but is there a way to improve this using async functions or something so that main UI is not blocked?

## Specs

MacBook Pro
2.3 GHz Intel Core i7
8 GB 1600 MHz DDR3
NVIDIA GeForce GT 650M 1024 MB

- Atom 1.12.6

- imdone-atom 2.0.19

## Steps

⌥T to load tasks. Atom grinds to a halt.
Screen says:

```
Loading ___ Tasks.
It's gonna be legen... wait for it.
```

And after a while:

```
Found 921 tasks in ___ ...
```

Then finally, the task screen appears. But it lags very badly, and Atom continues to have its UI blocked until I disable the plugin.

**Comment by jeveloper** [comment]
Hey there

I have a similar MBP , curious if you were able to get it run 4K at 60hz with this patch?

thanks @dalgleish

**Comment by piascikj** [comment]
Looks like there must be a correlation to the number of TODO comments found.
@jeveloper What patch? @dalgleish Is this from a project You can grant me access to for testing?

**Comment by piascikj** [comment]
I think I found a great project to test with.  I'll get back to you with the results.

**Comment by jeveloper** [comment]
@piascikj oh boy,my bad, i was searching a different project and this ticket came up, strange , it was related to 650M video card and 4k... 
nevermind hehe

**Comment by mediapathic** [comment]
Commenting to say that I have the same issue. Atom runs fine until I try to show a task list, and then it lags so hard that I literally have no idea how many search results there are, because I have been waiting for the last five minutes for it to finish so I can click on anything. I can say that it reports ~1400 text files that it's searching (it's a large directory of lots of small text fragments), so, I don't doubt that this is the issue and I am an outlier, but figuring out a way for this to not block UI would be great. imdone is actually the primary reason I'm using atom, so this means I'm going back to sublime until I can actually use the editor again.

**Comment by piascikj** [comment]
I have moved file watching to a worker thread which reduced some of the blocking, so it's more snappy now.  I'm currently working on [imdone-core/repo-worker-proxy.js](https://github.com/imdone/imdone-core/blob/master/lib/repo-worker-proxy.js) which will move all imdone repository processes to a worker.
